### PR TITLE
Split utils/prepare to make TextModels only usage at least works without Node.js polyfills

### PR DESCRIPTION
**Pull request by leaysgur**
This PR splits `utils/prepare.ts` into `prepare-text.ts` and `prepare-image.ts`.

### Current problem

When using only TextModel,

```ts
import { TextModel } from "@visheratin/web-ai";

const result = await TextModel.create("grammar-t5-efficient-tiny", false)
console.log(result.elapsed)
```

ends up with a runtime error for example in Vite app like this.

```
path-arg.ts:1 Uncaught ReferenceError: process is not defined
```

This happens because when you `import "@visheratin/web-ai";`, exported modules other than TextModel that depend on `jimp` are also preprocessed, and fail without Node.js polyfills.

There are several ways to solve this issue, but the simplest way I came up with was to `import "@visheratin/web-ai/dist/text";` directly.

But even this attempt `utils/prepare.ts` still depends on `jimp` and fails.

So with this PR, at least support to use only TextModels without any effort like seting up Node.js polyfills(which are completely useless at runtime).

- - - 

UPDATE: I only use Vite these days, but I noticed that this happens no matter what bundler is used. The commit message is a remnant of this. 😓

### CODE REVIEW

**Comment by visheratin** [comment]
Thank you very much for the PR! Generally, do you think that it would be a good idea to make image and text processing into sub-packages? This way, you'd be able to import only the required functionality, e.g., `@visheratin/web-ai/text`.

**Comment by leaysgur** [comment]
Yes. 😃 

In terms of usage, `@visheratin/web-ai/text` looks more natural(than `/dist/text`) if it's possible.

In terms of implementation, keep `jimp` isolated, at least until [browser support becomes more better](https://github.com/jimp-dev/jimp/issues/1194) is good idea for better accessibility.

**Comment by visheratin** [comment]
Yeah, the issues with Jimp are the reason why I keep an old version of it in dependencies.

I'll work on migrating Web AI to subpackages. It may take some time to figure out how to do it properly.

For now, I'll merge this PR and publish the new version of the package.

**Comment by visheratin** [comment]
Just published version 0.10.2. Thank you for your contribution!

**Comment by leaysgur** [comment]
Thank you, too!

**Pull request merged**
